# basic options 
title: Irene is the Queen
author: The Ruler of the universe 
email: ireneisthequeen@yahoo.com
description: Irene is the greatest and all will worship her 
twitter_username: kingoftheuniverse
github_username:  The ruler of the universe 

# Build settings
markdown: kramdown
theme: minima
